packages:
  - 'backend'
  - 'frontend'

onlyBuiltDependencies:
  - prisma
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - unrs-resolver
  - workerd

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: true
