// Mock para @nestjs/common (ESM → CJS compatible con Jest 29)
const actual = jest.requireActual('@nestjs/common');

module.exports = {
  ...actual,
  Injectable: actual.Injectable || (() => (target: any) => target),
  Controller: actual.Controller || (() => (target: any) => target),
  Module: actual.Module || (() => (target: any) => target),
  Param: actual.Param || (() => () => {}),
  Body: actual.Body || (() => () => {}),
  Query: actual.Query || (() => () => {}),
  Headers: actual.Headers || (() => () => {}),
  Req: actual.Req || (() => () => {}),
  Res: actual.Res || (() => () => {}),
  HttpCode: actual.HttpCode || (() => () => {}),
  HttpStatus: actual.HttpStatus || { OK: 200, CREATED: 201, NO_CONTENT: 204 },
  Get: actual.Get || (() => () => {}),
  Post: actual.Post || (() => () => {}),
  Put: actual.Put || (() => () => {}),
  Patch: actual.Patch || (() => () => {}),
  Delete: actual.Delete || (() => () => {}),
  UseGuards: actual.UseGuards || (() => () => {}),
  UsePipes: actual.UsePipes || (() => () => {}),
  UseInterceptors: actual.UseInterceptors || (() => () => {}),
  UseFilters: actual.UseFilters || (() => () => {}),
  SetMetadata: actual.SetMetadata || (() => () => {}),
  Global: actual.Global || (() => (target: any) => target),
  Catch: actual.Catch || (() => (target: any) => target),
  ExceptionFilter: actual.ExceptionFilter || class {},
  PipeTransform: actual.PipeTransform || class {},
  NestInterceptor: actual.NestInterceptor || class {},
  CanActivate: actual.CanActivate || class {},
  ExecutionContext: actual.ExecutionContext || class {},
  CallHandler: actual.CallHandler || class {},
  ArgumentsHost: actual.ArgumentsHost || class {},
  HttpException: actual.HttpException || class extends Error {},
  BadRequestException: actual.BadRequestException || class extends Error {},
  UnauthorizedException: actual.UnauthorizedException || class extends Error {},
  NotFoundException: actual.NotFoundException || class extends Error {},
  ForbiddenException: actual.ForbiddenException || class extends Error {},
  ConflictException: actual.ConflictException || class extends Error {},
  InternalServerErrorException: actual.InternalServerErrorException || class extends Error {},
  BadGatewayException: actual.BadGatewayException || class extends Error {},
  RequestTimeoutException: actual.RequestTimeoutException || class extends Error {},
  ServiceUnavailableException: actual.ServiceUnavailableException || class extends Error {},
  GatewayTimeoutException: actual.GatewayTimeoutException || class extends Error {},
  PayloadTooLargeException: actual.PayloadTooLargeException || class extends Error {},
  UnsupportedMediaTypeException: actual.UnsupportedMediaTypeException || class extends Error {},
  UnprocessableEntityException: actual.UnprocessableEntityException || class extends Error {},
  NotAcceptableException: actual.NotAcceptableException || class extends Error {},
  MethodNotAllowedException: actual.MethodNotAllowedException || class extends Error {},
  ImATeapotException: actual.ImATeapotException || class extends Error {},
  PreconditionFailedException: actual.PreconditionFailedException || class extends Error {},
};